name: Pylint

on:
  schedule:
    - cron: '0 0 * * SUN'  # Runs at 00:00 UTC on Sundays
  workflow_dispatch:      # Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List Python Files for Pylint
        run: |
          echo "Detecting Python files for Pylint analysis..."
          # Find all Python files, excluding the 'arcpy_tools' directory
          FILES=$(git ls-files '*.py' | grep -v '^arcpy_tools/')
          
          # Alternatively, use find to include all Python files
          # FILES=$(find . -type f -name "*.py" ! -path "./arcpy_tools/*")
          
          echo "Python files detected:"
          echo "$FILES"
          
          echo "Total Python files to analyze: $(echo "$FILES" | wc -l)"
          
          # Export FILES variable for the next step
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Analyze Code with Pylint
        run: |
          echo "Starting Pylint analysis..."
          
          # Access the FILES variable from environment
          for file in $FILES; do
            echo "------------------------------"
            echo "Pylint analysis for: $file"
            pylint "$file" --disable=duplicate-code
            echo "------------------------------"
          done
        continue-on-error: true  # Allows the workflow to continue even if Pylint fails
